[package]
name = "mizer-traktor-kontrol-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
mizer-traktor-kontrol-x1 = { path = "../../../../../components/connections/devices/traktor-kontrol-x1" }
mizer-devices = { path = "../../../../../components/connections/devices" }
mizer-node = { path = "../../../node" }
enum-iterator = "2.0"
num_enum = "0.7"
