[package]
name = "mizer-fixture-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../../node" }
mizer-fixtures = { path = "../../../../components/fixtures" }
