[package]
name = "mizer-traktor-kontrol-x1"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
tracing = "0.1"
anyhow = "1"
traktor-kontrol-x1 = { git = "https://github.com/maxjoehnk/traktor-kontrol-x1-rs.git" }
futures = "0.3"
flume = "0.11"
pinboard = "2.2"
uuid = { version = "1.8", features = ["v4"] }
