[workspace]
members = [
    "nodes/api",
    "nodes/protocols/artnet",
    "nodes/clock",
    "nodes/behaviors/conversion",
    "nodes/inputs",
    "nodes/protocols/midi",
    "nodes/protocols/opc",
    "nodes/protocols/osc",
    "nodes/oscillator",
    "nodes/pixels",
    "nodes/protocols/sacn",
    "nodes/behaviors/scripting",
    "nodes/behaviors/sequence",
    "nodes/video",
    "projects"
]

[lib]
name = "mizer"
path = "src/lib.rs"

[[bin]]
name = "mizer"
path = "src/main.rs"

[package]
name = "mizer"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[features]
default = ["export_metrics"]
export_metrics = ["metrics-runtime", "smol"]

[dependencies]
derive_more = "0.99"
env_logger = "0.7"
log = "0.4"
anyhow = "1"
gstreamer = "0.16"
smol = { version = "0.3", features = ["tokio02"], optional = true }
structopt = "0.3"
metrics = "0.12"
metrics-runtime = { version = "0.13", optional = true }
mizer-node-api = { path = "nodes/api" }
mizer-artnet-nodes = { path = "nodes/protocols/artnet" }
mizer-conversion-nodes = { path = "nodes/behaviors/conversion" }
mizer-input-nodes = { path = "nodes/inputs" }
mizer-sequence-nodes = { path = "nodes/behaviors/sequence" }
mizer-clock-nodes = { path = "nodes/clock" }
mizer-opc-nodes = { path = "nodes/protocols/opc" }
mizer-osc-nodes = { path = "nodes/protocols/osc" }
mizer-oscillator-nodes = { path = "nodes/oscillator" }
mizer-midi-nodes = { path = "nodes/protocols/midi" }
mizer-video-nodes = { path = "nodes/video" }
mizer-sacn-nodes = { path = "nodes/protocols/sacn" }
mizer-scripting-nodes = { path = "nodes/behaviors/scripting" }
mizer-pixel-nodes = { path = "nodes/pixels" }
mizer-project-files = { path = "projects" }
# TODO: check for a better way/a maintained library
multi_mut = "0.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "dmx_pixel_pushing"
harness = false
