[workspace]
members = [
    "api",
    "nodes/artnet",
    "nodes/clock",
    "nodes/conversion",
    "nodes/inputs",
    "nodes/log",
    "nodes/midi",
    "nodes/opc",
    "nodes/osc",
    "nodes/oscillator",
    "nodes/pixels",
    "nodes/sacn",
    "nodes/scripting",
    "nodes/sequence",
    "nodes/video",
    "projects"
]

[package]
name = "mizer"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[features]
default = ["export_metrics"]
export_metrics = ["metrics-runtime", "smol"]

[dependencies]
derive_more = "0.99"
env_logger = "0.7"
log = "0.4"
anyhow = "1"
gstreamer = "0.16"
smol = { version = "0.3", features = ["tokio02"], optional = true }
structopt = "0.3"
metrics = "0.12"
metrics-runtime = { version = "0.13", optional = true }
mizer-node-api = { path = "./api" }
mizer-artnet-nodes = { path = "./nodes/artnet" }
mizer-conversion-nodes = { path = "./nodes/conversion" }
mizer-input-nodes = { path = "./nodes/inputs" }
mizer-log-nodes = { path = "./nodes/log" }
mizer-sequence-nodes = { path = "./nodes/sequence" }
mizer-clock-nodes = { path = "./nodes/clock" }
mizer-opc-nodes = { path = "./nodes/opc" }
mizer-osc-nodes = { path = "./nodes/osc" }
mizer-oscillator-nodes = { path = "./nodes/oscillator" }
mizer-midi-nodes = { path = "./nodes/midi" }
mizer-video-nodes = { path = "./nodes/video" }
mizer-sacn-nodes = { path = "./nodes/sacn" }
mizer-scripting-nodes = { path = "./nodes/scripting" }
mizer-pixel-nodes = { path = "./nodes/pixels" }
mizer-project-files = { path = "./projects" }
# TODO: check for a better way/a maintained library
multi_mut = "0.1"
