[workspace]
members = [
    "api/grpc",
    "fixtures",
    "fixtures/open-fixture-library",
    "media",
    "nodes/api",
    "nodes/behaviors/conversion",
    "nodes/behaviors/scripting",
    "nodes/behaviors/sequence",
    "nodes/clock",
    "nodes/fixture",
    "nodes/inputs",
    "nodes/laser",
    "nodes/oscillator",
    "nodes/protocols/artnet",
    "nodes/protocols/midi",
    "nodes/protocols/opc",
    "nodes/protocols/osc",
    "nodes/protocols/sacn",
    "nodes/pixels",
    "nodes/video",
    "pipeline",
    "projects",
    "protocols/laser",
    "protocols/midi",
    "protocols/midi/device-profiles",
    "session"
]

[lib]
name = "mizer"
path = "src/lib.rs"

[[bin]]
name = "mizer"
path = "src/main.rs"

[package]
name = "mizer"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[features]
default = ["export_metrics"]
export_metrics = ["metrics-runtime", "smol"]

[dependencies]
derive_more = "0.99"
env_logger = "0.7"
log = "0.4"
anyhow = "1"
gstreamer = "0.16"
smol = { version = "0.3", features = ["tokio02"], optional = true }
structopt = "0.3"
metrics = "0.12"
metrics-runtime = { version = "0.13", optional = true }
mizer-media = { path = "media" }
mizer-project-files = { path = "projects" }
mizer-fixtures = { path = "fixtures" }
mizer-open-fixture-library-provider = { path = "fixtures/open-fixture-library" }
mizer-pipeline = { path = "pipeline" }
mizer-grpc-api = { path = "api/grpc" }
mizer-session = { path = "session" }
# TODO: check for a better way/a maintained library
multi_mut = "0.1"
tokio = { version = "0.2", features = ["rt-threaded", "macros", "time"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "dmx_pixel_pushing"
harness = false
