[workspace]
members = [
    "api/grpc",
    "components/devices",
    "components/fixtures",
    "components/fixtures/open-fixture-library",
    "components/media",
    "conversion",
    "runtime",
    "runtime/clock",
    "runtime/execution-planner",
    "runtime/injector",
    "runtime/layouts",
    "runtime/module",
    "runtime/session",
    "runtime/pipeline",
    "runtime/pipeline/node",
    "runtime/pipeline/nodes",
    "runtime/pipeline/nodes/behaviors/scripting",
    "runtime/pipeline/nodes/behaviors/sequence",
    "runtime/pipeline/nodes/clock",
    "runtime/pipeline/nodes/fixture",
    "runtime/pipeline/nodes/inputs",
    "runtime/pipeline/nodes/laser",
    "runtime/pipeline/nodes/behaviors/oscillator",
    "runtime/pipeline/nodes/protocols/dmx",
    "runtime/pipeline/nodes/protocols/midi",
    "runtime/pipeline/nodes/protocols/opc",
    "runtime/pipeline/nodes/protocols/osc",
    "runtime/pipeline/nodes/pixels",
    "runtime/pipeline/nodes/video",
    "runtime/pipeline/ports",
    "runtime/processing",
    "runtime/projects",
    "protocols/dmx",
    "protocols/laser",
    "protocols/midi",
    "protocols/midi/device-profiles",
    "protocols/osc",
]

[lib]
name = "mizer"
path = "src/lib.rs"
bench = false

[[bin]]
name = "mizer"
path = "src/main.rs"
bench = false

[package]
name = "mizer"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"
license = "GNU AGPLv3"

[dependencies]
derive_more = "0.99"
env_logger = "0.7"
log = "0.4"
anyhow = "1"
gstreamer = "0.16"
structopt = "0.3"
metrics = "0.14"
mizer-media = { path = "components/media" }
mizer-project-files = { path = "runtime/projects" }
mizer-fixtures = { path = "components/fixtures" }
mizer-open-fixture-library-provider = { path = "components/fixtures/open-fixture-library" }
mizer-pipeline = { path = "runtime/pipeline" }
mizer-grpc-api = { path = "api/grpc" }
mizer-session = { path = "runtime/session" }
mizer-devices = { path = "components/devices" }
mizer-runtime = { path = "runtime" }
mizer-execution-planner = { path = "runtime/execution-planner" }
mizer-node = { path = "runtime/pipeline/node" }
mizer-protocol-dmx = { path = "protocols/dmx" }
mizer-processing = { path = "runtime/processing" }
mizer-module = { path = "runtime/module" }
tokio = { version = "0.2", features = ["rt-threaded", "macros", "time"] }

[dev-dependencies]
test-case = "1.0"
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "dmx_pixel_pushing"
harness = false

[profile.bench]
lto = true
