[workspace]
members = [
    "api",
    "api/grpc",
    "components/connections",
    "components/connections/devices",
    "components/connections/protocols/dmx",
    "components/connections/protocols/laser",
    "components/connections/protocols/midi",
    "components/connections/protocols/midi/device-profiles",
    "components/connections/protocols/osc",
    "components/fixtures",
    "components/fixtures/open-fixture-library",
    "components/media",
    "components/sequencer",
    "runtime",
    "runtime/clock",
    "runtime/execution-planner",
    "runtime/injector",
    "runtime/layouts",
    "runtime/module",
    "runtime/session",
    "runtime/pipeline",
    "runtime/pipeline/node",
    "runtime/pipeline/nodes",
    "runtime/pipeline/nodes/behaviors/envelope",
    "runtime/pipeline/nodes/behaviors/oscillator",
    "runtime/pipeline/nodes/behaviors/port-operations",
    "runtime/pipeline/nodes/behaviors/scripting",
    "runtime/pipeline/nodes/behaviors/sequence",
    "runtime/pipeline/nodes/clock",
    "runtime/pipeline/nodes/fixture",
    "runtime/pipeline/nodes/inputs",
    "runtime/pipeline/nodes/laser",
    "runtime/pipeline/nodes/protocols/dmx",
    "runtime/pipeline/nodes/protocols/midi",
    "runtime/pipeline/nodes/protocols/opc",
    "runtime/pipeline/nodes/protocols/osc",
    "runtime/pipeline/nodes/pixels",
    "runtime/pipeline/nodes/video",
    "runtime/pipeline/ports",
    "runtime/processing",
    "runtime/projects",
    "ui",
    "ui/ffi",
    "util",
]

[lib]
name = "mizer"
path = "src/lib.rs"
bench = false

[[bin]]
name = "mizer"
path = "src/main.rs"
bench = false

[package]
name = "mizer"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"
license = "GNU AGPLv3"

[features]
default = ["ui"]
ui = ["mizer-ui"]
tracy = ["profiling/profile-with-tracy"]

[dependencies]
derive_more = "0.99"
env_logger = "0.7"
log = "0.4"
anyhow = "1"
gstreamer = "0.17"
structopt = "0.3"
metrics = "0.14"
mizer-media = { path = "components/media" }
mizer-project-files = { path = "runtime/projects" }
mizer-fixtures = { path = "components/fixtures" }
mizer-open-fixture-library-provider = { path = "components/fixtures/open-fixture-library" }
mizer-pipeline = { path = "runtime/pipeline" }
mizer-api = { path = "api" }
mizer-grpc-api = { path = "api/grpc" }
mizer-session = { path = "runtime/session" }
mizer-connections = { path = "components/connections" }
mizer-devices = { path = "components/connections/devices" }
mizer-sequencer = { path = "components/sequencer" }
mizer-runtime = { path = "runtime" }
mizer-execution-planner = { path = "runtime/execution-planner" }
mizer-node = { path = "runtime/pipeline/node" }
mizer-nodes = { path = "runtime/pipeline/nodes" }
mizer-layouts = { path = "runtime/layouts" }
mizer-clock = { path = "runtime/clock" }
mizer-protocol-dmx = { path = "components/connections/protocols/dmx" }
mizer-protocol-midi = { path = "components/connections/protocols/midi" }
mizer-processing = { path = "runtime/processing" }
mizer-module = { path = "runtime/module" }
mizer-ui = { path = "ui", optional = true }
mizer-util = { path = "util" }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros", "time", "rt"] }
futures = "0.3"
pinboard = "2.1"
dashmap = "4"
flume = "0.10"
profiling = "1.0"

[dev-dependencies]
test-case = "1.0"
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "dmx_pixel_pushing"
harness = false

[profile.bench]
lto = true
