[package]
name = "mizer-laser-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
mizer-node-api = { path = "../api" }
mizer-protocol-laser = { path = "../../protocols/laser" }
