[package]
name = "mizer-midi-device-profiles"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
rhai = { version = "0.19", features = ["sync"] }
mizer-protocol-midi = { path = "../" }
