[package]
name = "mizer-layouts"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../pipeline/node" }
pinboard = "2.1"
