[package]
name = "mizer-laser-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
mizer-protocol-laser = { path = "../../../../protocols/laser" }
mizer-devices = { path = "../../../../components/devices" }
mizer-node = { path = "../../node" }
