[package]
name = "mizer-artnet-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
artnet_protocol = { git = "https://github.com/Trangar/artnet_protocol" }
mizer-node-api = { path = "../../api" }
log = "0.4"
