[package]
name = "mizer-protocol-dmx"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
artnet_protocol = "0.4"
sacn = "0.4"
log = "0.4"
mizer-processing = { path = "../../../../runtime/processing" }
mizer-module = { path = "../../../../runtime/module" }
mizer-commander = { path = "../../../../runtime/commander" }
profiling = "1"
enum_dispatch = "0.3.7"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
