[package]
name = "mizer-midi-messages"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
