[general]
language = "en"
auto_load_last_project = true

[paths]
midi_device_profiles = "crates/components/connections/protocols/midi/device-profiles/profiles"
media_storage = ".storage"

[paths.fixture_libraries]
open_fixture_library = "crates/components/fixtures/open-fixture-library/.fixtures"
qlcplus = "crates/components/fixtures/qlcplus/.fixtures"
gdtf = "crates/components/fixtures/gdtf/.fixtures"
mizer = "crates/components/fixtures/mizer-definitions/.fixtures"
