[general]
language = "en"
auto_load_last_project = true

[paths]
media_storage = ".storage"
midi_device_profiles = [
    "crates/components/connections/protocols/midi/device-profiles/profiles",
    "~/Documents/Mizer/Midi Device Profiles",
]

[paths.fixture_libraries]
open_fixture_library = [
    "crates/components/fixtures/open-fixture-library/.fixtures",
    "~/Documents/Mizer/Fixture Definitions/Open Fixture Library",
]
qlcplus = [
    "crates/components/fixtures/qlcplus/.fixtures",
    "~/Documents/Mizer/Fixture Definitions/QLC+",
]
gdtf = [
    "crates/components/fixtures/gdtf/.fixtures",
    "~/Documents/Mizer/Fixture Definitions/GDTF",
]
mizer = [
    "crates/components/fixtures/mizer-definitions/.fixtures",
    "~/Documents/Mizer/Fixture Definitions/Mizer",
]
