[package]
name = "mizer-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../node" }
mizer-clock-nodes = { path = "clock" }
mizer-oscillator-nodes = { path = "behaviors/oscillator" }
mizer-port-operation-nodes = { path = "behaviors/port-operations" }
mizer-dmx-nodes = { path = "protocols/dmx" }
mizer-scripting-nodes = { path = "behaviors/scripting" }
mizer-sequence-nodes = { path = "behaviors/sequence" }
mizer-fixture-nodes = { path = "fixture" }
mizer-laser-nodes = { path = "laser" }
mizer-input-nodes = { path = "inputs" }
mizer-midi-nodes = { path = "protocols/midi" }
mizer-pixel-nodes = { path = "pixels" }
mizer-opc-nodes = { path = "protocols/opc" }
mizer-osc-nodes = { path ="protocols/osc" }
mizer-video-nodes = { path = "video" }
derive_more = "0.99"
