[package]
name = "mizer-proto"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
protobuf = "2.18"
serde_derive = "1"

[build-dependencies]
protoc-rust = "2.18"
