[hotkeys.global]
layout_view = "f1"
plan_view = "f2"
previz_view = "f3"
nodes_view = "f4"
sequencer_view = "f5"
programmer_view = "f6"
media_view = "f7"
connections_view = "f8"
fixture_patch_view = "f9"
session_view = "f10"

[hotkeys.layouts]
add_layout = "alt+a"

[hotkeys.programmer]
select_all = "ctrl+a"
clear = "backspace"
store = "insert"
highlight = "home"

[hotkeys.patch]
add_fixture = "alt+a"
select_all = "ctrl+a"
clear = "backspace"
delete = "delete"

[hotkeys.nodes]
add_node = "alt+a"
