[hotkeys.global]
layout_view = "f1"
plan_view = "f2"
previz_view = "f3"
nodes_view = "f4"
sequencer_view = "f5"
programmer_view = "f6"
presets_view = "f7"
effects_view = "f8"
media_view = "f9"
surfaces_view = "f10"
connections_view = "f11"
fixture_patch_view = "f12"

[hotkeys.layouts]
add_layout = "alt+a"

[hotkeys.programmer]
select_all = "ctrl+a"
clear = "backspace"
store = "insert"
highlight = "home"

[hotkeys.patch]
add_fixture = "alt+a"
select_all = "ctrl+a"
clear = "backspace"
delete = "delete"
assign_group = "ctrl+g"

[hotkeys.nodes]
add_node = "alt+a"

[hotkeys.sequencer]
add_sequence = "alt+a"
delete = "delete"
