[package]
name = "mizer-artnet-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
artnet_protocol = "0.2"
mizer-node-api = { path = "../../api" }
log = "0.4"
