[build]
rustflags = ["-C", "target-cpu=native"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-Wl,-rpath,@executable_path"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-Wl,-rpath,$ORIGIN/lib"]
