[package]
name = "mizer-pixel-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
mizer-node-api = { path = "../../node-api" }
log = "0.4"
serde = { version = "1", features = ["derive"] }
