[package]
name = "mizer-conversion-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
mizer-node-api = { path = "../../../node-api" }
log = "0.4"

[dev-dependencies]
test-case = "1.0"
mizer-node-api = { path = "../../../node-api", features = ["testing"] }
