[package]
name = "mizer-osc-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
mizer-node-api = { path = "../../../node-api" }
rosc = "0.4"
crossbeam-channel = "0.4"
lazy_static = "1.4"
log = "0.4"
