[package]
name = "mizer-ui"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
mizer-api = { path = "../api" }
flutter-engine = { git = "https://github.com/maxjoehnk/flutter-rs.git" }
flutter-glfw = { git = "https://github.com/maxjoehnk/flutter-rs.git" }
protobuf = "2.18"
smol = "1.2"

[build-dependencies]
flutter-tools = { git = "https://github.com/maxjoehnk/flutter-rs.git" }

