name: mizer
description: UI for Mizer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  grpc: ^3.0.0
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.3
  material_design_icons_flutter: ^4.0.0
  file_selector_platform_interface: ^2.0.0
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  mockito: ^5.0.0
  bloc_test: ^8.0.0-nullsafety.1

flutter:
  uses-material-design: true
