name: mizer
description: UI for Mizer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  grpc: ^3.0.0
  fixnum: ^1.0.0
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0
  provider: ^6.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  multicast_dns: ^0.3.1
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
      ref: 85dde09
  select_form_field: ^2.2.0
  collection: ^1.15.0
  nativeshell: 0.1.9
  flutter_svg: ^0.22.0
  flex_color_picker: ^2.1.2
  keyboard_shortcuts:
    git:
      url: https://github.com/AntoineMarcel/keyboard_shortcuts
      ref: d935831

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.0
  mockito: ^5.0.0
  bloc_test: ^8.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
