[package]
name = "mizer-grpc-api"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
mizer-fixtures = { path = "../../fixtures" }
mizer-media = { path = "../../media" }
mizer-pipeline = { path = "../../pipeline" }
mizer-project-files = { path = "../../projects" }
grpc = { git = "https://github.com/maxjoehnk/grpc-rust.git" }
grpc-protobuf = { git = "https://github.com/maxjoehnk/grpc-rust.git" }
futures = "0.3"
protobuf = "2.18"
tokio = { version = "0.2" }

[build-dependencies]
protoc-rust-grpc = { git = "https://github.com/maxjoehnk/grpc-rust.git" }
