[package]
name = "mizer-plan-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
mizer-node = { path = "../../node" }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
mizer-plan = { path = "../../../../components/plan" }
mizer-fixtures = { path = "../../../../components/fixtures" }
mizer-util = { path = "../../../../util" }
mizer-wgpu = { path = "../../../wgpu" }
