on: [push]

name: Benchmarks

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Install Gstreamer
        run: sudo apt-get update && sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libasound2-dev libavahi-client-dev protobuf-compiler gnuplot-nox
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Run benchmark
        run: cargo bench --workspace -- --output-format bencher | tee output.txt
      - name: Store benchmark results
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: output.txt
