---
on: [push]

name: Benchmarks

jobs:
  benchmarks:
    if: false
    runs-on: ubuntu-20.04
    steps:
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            libasound2-dev \
            libavahi-client-dev \
            xorg-dev \
            libgtk-3-dev \
            libclang-dev \
            libudev-dev \
            curl \
            lld \
            ffmpeg \
            libavcodec-dev \
            libavdevice-dev \
            libavfilter-dev \
            libavformat-dev \
            libavutil-dev \
            libpostproc-dev \
            libswresample-dev \
            libswscale-dev \
            libass-dev \
            libfreetype6-dev \
            libgnutls28-dev \
            libsdl2-dev \
            libtool \
            libva-dev \
            libvdpau-dev \
            libvorbis-dev \
            libxcb1-dev \
            libxcb-shm0-dev \
            libxcb-xfixes0-dev \
            zlib1g-dev \
            libx264-dev \
            libx265-dev \
            libnuma-dev \
            libvpx-dev \
            libmp3lame-dev \
            libopus-dev \
            libraw1394-dev \
            libdc1394-dev \
            libavc1394-dev \
            libiec61883-dev \
            libjack-dev \
            libfaad-dev \
            libgsm1-dev \
            libzmq3-dev \
            libssh-dev \
            libbluray-dev \
            libopenmpt-dev \
            ocl-icd-opencl-dev \
            libogg-dev \
            libspeex-dev \
            libtheora-dev \
            flite1-dev \
            libchromaprint-dev \
            libopenal-dev \
            libcdio-dev \
            libcaca-dev \
            libpocketsphinx-dev \
            libsphinxbase-dev \
            libbs2b-dev \
            liblilv-dev \
            libsratom-dev \
            libsord-dev \
            libserd-dev \
            librubberband-dev \
            libsamplerate0-dev \
            libmysofa-dev \
            libvidstab-dev \
            libgme-dev \
            librabbitmq-dev \
            libdav1d-dev \
            libzvbi-dev \
            libsnappy-dev \
            libaom-dev \
            libcodec2-dev \
            libshine-dev \
            libtwolame-dev \
            libwebp-dev \
            libxvidcore-dev \
            libsoxr-dev \
            libcdio-paranoia-dev \
            libcdio-cdda-dev \
            libsrt-gnutls-dev \
            libmfx-dev \
            libvorbis-dev \
            libwavpack-dev
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
      - uses: Swatinem/rust-cache@v2
      - name: Run benchmark
        run: cargo bench --workspace -- --output-format bencher | tee output.txt
#      - name: Store benchmark results
#        uses: rhysd/github-action-benchmark@v1
#        with:
#          tool: 'cargo'
#          output-file-path: output.txt
