---
on: [push]

name: Build

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libasound2-dev libavahi-client-dev xorg-dev libgtk-3-dev libclang-dev libudev-dev curl
      - name: Install Protoc 3.17.3
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-x86_64.zip
          unzip protoc-3.17.3-linux-x86_64.zip
          mkdir -p "$HOME/.local/bin"
          cp bin/protoc "$HOME/.local/bin/"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build Headless
        run: make build-headless
      - uses: actions/upload-artifact@v3
        with:
          name: linux-headless
          path: target/release/mizer
          if-no-files-found: error
      - name: Build
        run: make build-release
      - name: Package
        run: make package
      - uses: actions/upload-artifact@v3
        with:
          name: linux-full
          path: artifact
          if-no-files-found: error
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Install build dependencies
        run: brew install protobuf gstreamer gst-plugins-base gst-plugins-bad
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build
        run: make build-release
        continue-on-error: true
      - name: Package
        run: make package
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: macos-full
          path: artifact

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install build dependencies
        run: choco install protoc make wget
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get flutter deps
        run: flutter pub get
        working-directory: ui
      - name: Build
        run: make build-release-no-gst
        continue-on-error: true
      - name: Package
        run: make package
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: windows-full
          path: artifact
