on: [push]

name: Build

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Install Gstreamer
        run: sudo apt-get update && sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libasound2-dev libavahi-client-dev protobuf-compiler
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v2
        with:
          name: linux-server
          path: target/release/mizer
          if-no-files-found: error
  build-client-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install flutter linux deps
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
        working-directory: ui
      - run: flutter build linux
        working-directory: ui
      - uses: actions/upload-artifact@v2
        with:
          name: linux-client
          path: ui/build/linux/x64/release/bundle
          if-no-files-found: error
  build-client-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
        working-directory: ui
      - run: flutter build apk
        working-directory: ui
      - uses: actions/upload-artifact@v2
        with:
          name: android-client
          path: ui/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
  build-client-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
        working-directory: ui
      - run: flutter build macos
        working-directory: ui
      - uses: actions/upload-artifact@v2
        with:
          name: macos-client
          path: ui/build/macos/Build/Products/Release/
          if-no-files-found: error
  build-client-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
        working-directory: ui
      - run: flutter build windows
        working-directory: ui
      - uses: actions/upload-artifact@v2
        with:
          name: windows-client
          path: ui/build/windows/runner/release
          if-no-files-found: error
