on: [push]

name: Build

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Install Gstreamer
        run: sudo apt-get update && sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev libasound2-dev libavahi-client-dev protobuf-compiler
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Clippy Checks
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions/upload-artifact@v2
        with:
          name: mizer
          path: target/release/mizer
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
        working-directory: ui
      - run: flutter build linux
        working-directory: ui
      - uses: actions/upload-artifact@v2
        with:
          name: linux-client
          path: ui/build/linux/release/bundle/
