[package]
name = "mizer-gamepad-nodes"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
mizer-gamepads = { path = "../../../../../components/connections/devices/gamepads" }
mizer-devices = { path = "../../../../../components/connections/devices" }
mizer-node = { path = "../../../node" }
mizer-util = { path = "../../../../../util" }
